/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Houston API
 * OpenAPI spec version: 0.1.0
 */
import customInstance from './mutator';
export interface BodyUploadModel {
  file: Blob;
  name: string;
  version: string;
  tags?: string[];
  description: string;
}

export interface BodyUploadReplay {
  file: Blob;
  filename?: string | null;
  platform?: string | null;
  tags?: string[];
  description?: string | null;
  permanent?: boolean;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface Model {
  model_id: string;
  name: string;
  path: string;
  tags: string[];
  version: string;
  description?: string;
  upload_time: string;
  size: number;
}

export interface ModelListResponse {
  models: Model[];
  total: number;
}

export interface Replay {
  replay_id: string;
  platform?: string | null;
  filename?: string | null;
  path: string;
  description?: string | null;
  start_time?: string | null;
  end_time?: string | null;
  upload_time: string;
  permanent?: boolean;
  tags?: string[];
}

export interface ReplayListResponse {
  replays: Replay[];
  total: number;
}

export interface ReplayerResponse {
  replayer_id: string;
  name: string;
  port: number;
  replay_ids: string[];
  start_time: number;
  fabric_pid: number;
  replay_pid: number;
}

export interface StartReplayerRequest {
  /** Logical name for this replayer run */
  name: string;
  /** List of replay IDs to process */
  replay_ids: string[];
}

export type ListReplaysParams = {
page?: number | null;
tags?: string[] | null;
};

export type ListModelsParams = {
page?: number | null;
};

export type uploadReplayResponse200 = {
  data: Replay
  status: 200
}

export type uploadReplayResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type uploadReplayResponseSuccess = (uploadReplayResponse200) & {
  headers: Headers;
};
export type uploadReplayResponseError = (uploadReplayResponse422) & {
  headers: Headers;
};

export type uploadReplayResponse = (uploadReplayResponseSuccess | uploadReplayResponseError)

export const getUploadReplayUrl = () => {




  return `http://localhost:8085/replays/`
}

/**
 * @summary Upload Replay
 */
export const uploadReplay = async (bodyUploadReplay: BodyUploadReplay, options?: RequestInit): Promise<Replay> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadReplay.file);
if(bodyUploadReplay.filename !== undefined && bodyUploadReplay.filename !== null) {
 formData.append(`filename`, bodyUploadReplay.filename);
 }
if(bodyUploadReplay.platform !== undefined && bodyUploadReplay.platform !== null) {
 formData.append(`platform`, bodyUploadReplay.platform);
 }
if(bodyUploadReplay.tags !== undefined) {
 bodyUploadReplay.tags.forEach(value => formData.append(`tags`, value));
 }
if(bodyUploadReplay.description !== undefined && bodyUploadReplay.description !== null) {
 formData.append(`description`, bodyUploadReplay.description);
 }
if(bodyUploadReplay.permanent !== undefined) {
 formData.append(`permanent`, bodyUploadReplay.permanent.toString())
 }

  return customInstance<Replay>(getUploadReplayUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);
}



export type listReplaysResponse200 = {
  data: ReplayListResponse
  status: 200
}

export type listReplaysResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listReplaysResponseSuccess = (listReplaysResponse200) & {
  headers: Headers;
};
export type listReplaysResponseError = (listReplaysResponse422) & {
  headers: Headers;
};

export type listReplaysResponse = (listReplaysResponseSuccess | listReplaysResponseError)

export const getListReplaysUrl = (params?: ListReplaysParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["tags"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8085/replays/?${stringifiedParams}` : `http://localhost:8085/replays/`
}

/**
 * @summary List Replays
 */
export const listReplays = async (params?: ListReplaysParams, options?: RequestInit): Promise<ReplayListResponse> => {

  return customInstance<ReplayListResponse>(getListReplaysUrl(params),
  {
    ...options,
    method: 'GET'


  }
);
}



export type getReplayFileResponse200 = {
  data: unknown
  status: 200
}

export type getReplayFileResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getReplayFileResponseSuccess = (getReplayFileResponse200) & {
  headers: Headers;
};
export type getReplayFileResponseError = (getReplayFileResponse422) & {
  headers: Headers;
};

export type getReplayFileResponse = (getReplayFileResponseSuccess | getReplayFileResponseError)

export const getGetReplayFileUrl = (replayId: string,) => {




  return `http://localhost:8085/replays/${replayId}`
}

/**
 * @summary Get Replay File
 */
export const getReplayFile = async (replayId: string, options?: RequestInit): Promise<unknown> => {

  return customInstance<unknown>(getGetReplayFileUrl(replayId),
  {
    ...options,
    method: 'GET'


  }
);
}



export type updateReplayResponse200 = {
  data: Replay
  status: 200
}

export type updateReplayResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateReplayResponseSuccess = (updateReplayResponse200) & {
  headers: Headers;
};
export type updateReplayResponseError = (updateReplayResponse422) & {
  headers: Headers;
};

export type updateReplayResponse = (updateReplayResponseSuccess | updateReplayResponseError)

export const getUpdateReplayUrl = (replayId: string,) => {




  return `http://localhost:8085/replays/${replayId}`
}

/**
 * @summary Update Replay
 */
export const updateReplay = async (replayId: string,
    replay: Replay, options?: RequestInit): Promise<Replay> => {

  return customInstance<Replay>(getUpdateReplayUrl(replayId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(replay)
  }
);
}



export type getReplayInfoResponse200 = {
  data: Replay
  status: 200
}

export type getReplayInfoResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getReplayInfoResponseSuccess = (getReplayInfoResponse200) & {
  headers: Headers;
};
export type getReplayInfoResponseError = (getReplayInfoResponse422) & {
  headers: Headers;
};

export type getReplayInfoResponse = (getReplayInfoResponseSuccess | getReplayInfoResponseError)

export const getGetReplayInfoUrl = (replayId: string,) => {




  return `http://localhost:8085/replays/${replayId}/info`
}

/**
 * @summary Get Replay Info
 */
export const getReplayInfo = async (replayId: string, options?: RequestInit): Promise<Replay> => {

  return customInstance<Replay>(getGetReplayInfoUrl(replayId),
  {
    ...options,
    method: 'GET'


  }
);
}



export type getReplayersResponse200 = {
  data: ReplayerResponse[]
  status: 200
}

export type getReplayersResponseSuccess = (getReplayersResponse200) & {
  headers: Headers;
};
;

export type getReplayersResponse = (getReplayersResponseSuccess)

export const getGetReplayersUrl = () => {




  return `http://localhost:8085/replayer`
}

/**
 * Retrieve all running replayer metadata from the pid storage.
 * @summary List all active replayers
 */
export const getReplayers = async ( options?: RequestInit): Promise<ReplayerResponse[]> => {

  return customInstance<ReplayerResponse[]>(getGetReplayersUrl(),
  {
    ...options,
    method: 'GET'


  }
);
}



export type createReplayerResponse201 = {
  data: ReplayerResponse
  status: 201
}

export type createReplayerResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createReplayerResponseSuccess = (createReplayerResponse201) & {
  headers: Headers;
};
export type createReplayerResponseError = (createReplayerResponse422) & {
  headers: Headers;
};

export type createReplayerResponse = (createReplayerResponseSuccess | createReplayerResponseError)

export const getCreateReplayerUrl = () => {




  return `http://localhost:8085/replayer`
}

/**
 * Spawns background process pairs (Fabric server & Replayer) and records their execution metadata.
 * @summary Start a new replayer process pair
 */
export const createReplayer = async (startReplayerRequest: StartReplayerRequest, options?: RequestInit): Promise<ReplayerResponse> => {

  return customInstance<ReplayerResponse>(getCreateReplayerUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(startReplayerRequest)
  }
);
}



export type terminateReplayerResponse204 = {
  data: void
  status: 204
}

export type terminateReplayerResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type terminateReplayerResponseSuccess = (terminateReplayerResponse204) & {
  headers: Headers;
};
export type terminateReplayerResponseError = (terminateReplayerResponse422) & {
  headers: Headers;
};

export type terminateReplayerResponse = (terminateReplayerResponseSuccess | terminateReplayerResponseError)

export const getTerminateReplayerUrl = (replayerId: string,) => {




  return `http://localhost:8085/replayer/${replayerId}`
}

/**
 * Terminates fabric and replayer processes associated with the given replayer ID via SIGTERM.
 * @summary Stop a replayer process pair
 */
export const terminateReplayer = async (replayerId: string, options?: RequestInit): Promise<void> => {

  return customInstance<void>(getTerminateReplayerUrl(replayerId),
  {
    ...options,
    method: 'DELETE'


  }
);
}



export type uploadModelResponse200 = {
  data: Model
  status: 200
}

export type uploadModelResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type uploadModelResponseSuccess = (uploadModelResponse200) & {
  headers: Headers;
};
export type uploadModelResponseError = (uploadModelResponse422) & {
  headers: Headers;
};

export type uploadModelResponse = (uploadModelResponseSuccess | uploadModelResponseError)

export const getUploadModelUrl = () => {




  return `http://localhost:8085/models/`
}

/**
 * @summary Upload Model
 */
export const uploadModel = async (bodyUploadModel: BodyUploadModel, options?: RequestInit): Promise<Model> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadModel.file);
formData.append(`name`, bodyUploadModel.name);
formData.append(`version`, bodyUploadModel.version);
if(bodyUploadModel.tags !== undefined) {
 bodyUploadModel.tags.forEach(value => formData.append(`tags`, value));
 }
formData.append(`description`, bodyUploadModel.description);

  return customInstance<Model>(getUploadModelUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);
}



export type listModelsResponse200 = {
  data: ModelListResponse
  status: 200
}

export type listModelsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listModelsResponseSuccess = (listModelsResponse200) & {
  headers: Headers;
};
export type listModelsResponseError = (listModelsResponse422) & {
  headers: Headers;
};

export type listModelsResponse = (listModelsResponseSuccess | listModelsResponseError)

export const getListModelsUrl = (params?: ListModelsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8085/models/?${stringifiedParams}` : `http://localhost:8085/models/`
}

/**
 * @summary List Models
 */
export const listModels = async (params?: ListModelsParams, options?: RequestInit): Promise<ModelListResponse> => {

  return customInstance<ModelListResponse>(getListModelsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);
}



export type getModelFileResponse200 = {
  data: unknown
  status: 200
}

export type getModelFileResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getModelFileResponseSuccess = (getModelFileResponse200) & {
  headers: Headers;
};
export type getModelFileResponseError = (getModelFileResponse422) & {
  headers: Headers;
};

export type getModelFileResponse = (getModelFileResponseSuccess | getModelFileResponseError)

export const getGetModelFileUrl = (modelId: string,) => {




  return `http://localhost:8085/models/${modelId}`
}

/**
 * @summary Get Model File
 */
export const getModelFile = async (modelId: string, options?: RequestInit): Promise<unknown> => {

  return customInstance<unknown>(getGetModelFileUrl(modelId),
  {
    ...options,
    method: 'GET'


  }
);
}



export type getModelInfoResponse200 = {
  data: Model
  status: 200
}

export type getModelInfoResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getModelInfoResponseSuccess = (getModelInfoResponse200) & {
  headers: Headers;
};
export type getModelInfoResponseError = (getModelInfoResponse422) & {
  headers: Headers;
};

export type getModelInfoResponse = (getModelInfoResponseSuccess | getModelInfoResponseError)

export const getGetModelInfoUrl = (modelId: string,) => {




  return `http://localhost:8085/models/${modelId}/info`
}

/**
 * @summary Get Model Info
 */
export const getModelInfo = async (modelId: string, options?: RequestInit): Promise<Model> => {

  return customInstance<Model>(getGetModelInfoUrl(modelId),
  {
    ...options,
    method: 'GET'


  }
);
}
