/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
export interface BodyUploadModelModelsPost {
  file: Blob;
  name: string;
  version: string;
  tags?: string[];
  description: string;
}

export interface BodyUploadReplayReplaysPost {
  file: Blob;
  filename?: string | null;
  platform?: string | null;
  tags?: string[];
  description?: string | null;
  permanent?: boolean;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface Model {
  model_id: string;
  name: string;
  path: string;
  tags: string[];
  version: string;
  description?: string;
  upload_time: string;
  size: number;
}

export interface Replay {
  replay_id: string;
  platform?: string | null;
  filename?: string | null;
  path: string;
  description?: string | null;
  start_time?: string | null;
  end_time?: string | null;
  upload_time: string;
  permanent?: boolean;
  tags?: string[];
}

export type ListReplaysReplaysGetParams = {
page?: number | null;
};

export type ListModelsModelsGetParams = {
page?: number | null;
};

export type uploadReplayReplaysPostResponse200 = {
  data: Replay
  status: 200
}

export type uploadReplayReplaysPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type uploadReplayReplaysPostResponseSuccess = (uploadReplayReplaysPostResponse200) & {
  headers: Headers;
};
export type uploadReplayReplaysPostResponseError = (uploadReplayReplaysPostResponse422) & {
  headers: Headers;
};

export type uploadReplayReplaysPostResponse = (uploadReplayReplaysPostResponseSuccess | uploadReplayReplaysPostResponseError)

export const getUploadReplayReplaysPostUrl = () => {




  return `http://localhost:8080/replays/`
}

/**
 * @summary Upload Replay
 */
export const uploadReplayReplaysPost = async (bodyUploadReplayReplaysPost: BodyUploadReplayReplaysPost, options?: RequestInit): Promise<uploadReplayReplaysPostResponse> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadReplayReplaysPost.file);
if(bodyUploadReplayReplaysPost.filename !== undefined && bodyUploadReplayReplaysPost.filename !== null) {
 formData.append(`filename`, bodyUploadReplayReplaysPost.filename);
 }
if(bodyUploadReplayReplaysPost.platform !== undefined && bodyUploadReplayReplaysPost.platform !== null) {
 formData.append(`platform`, bodyUploadReplayReplaysPost.platform);
 }
if(bodyUploadReplayReplaysPost.tags !== undefined) {
 bodyUploadReplayReplaysPost.tags.forEach(value => formData.append(`tags`, value));
 }
if(bodyUploadReplayReplaysPost.description !== undefined && bodyUploadReplayReplaysPost.description !== null) {
 formData.append(`description`, bodyUploadReplayReplaysPost.description);
 }
if(bodyUploadReplayReplaysPost.permanent !== undefined) {
 formData.append(`permanent`, bodyUploadReplayReplaysPost.permanent.toString())
 }

  const res = await fetch(getUploadReplayReplaysPostUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: uploadReplayReplaysPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadReplayReplaysPostResponse
}



export type listReplaysReplaysGetResponse200 = {
  data: unknown
  status: 200
}

export type listReplaysReplaysGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listReplaysReplaysGetResponseSuccess = (listReplaysReplaysGetResponse200) & {
  headers: Headers;
};
export type listReplaysReplaysGetResponseError = (listReplaysReplaysGetResponse422) & {
  headers: Headers;
};

export type listReplaysReplaysGetResponse = (listReplaysReplaysGetResponseSuccess | listReplaysReplaysGetResponseError)

export const getListReplaysReplaysGetUrl = (params?: ListReplaysReplaysGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8080/replays/?${stringifiedParams}` : `http://localhost:8080/replays/`
}

/**
 * @summary List Replays
 */
export const listReplaysReplaysGet = async (params?: ListReplaysReplaysGetParams, options?: RequestInit): Promise<listReplaysReplaysGetResponse> => {

  const res = await fetch(getListReplaysReplaysGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listReplaysReplaysGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listReplaysReplaysGetResponse
}



export type getReplayFileReplaysReplayIdGetResponse200 = {
  data: unknown
  status: 200
}

export type getReplayFileReplaysReplayIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getReplayFileReplaysReplayIdGetResponseSuccess = (getReplayFileReplaysReplayIdGetResponse200) & {
  headers: Headers;
};
export type getReplayFileReplaysReplayIdGetResponseError = (getReplayFileReplaysReplayIdGetResponse422) & {
  headers: Headers;
};

export type getReplayFileReplaysReplayIdGetResponse = (getReplayFileReplaysReplayIdGetResponseSuccess | getReplayFileReplaysReplayIdGetResponseError)

export const getGetReplayFileReplaysReplayIdGetUrl = (replayId: string,) => {




  return `http://localhost:8080/replays/${replayId}`
}

/**
 * @summary Get Replay File
 */
export const getReplayFileReplaysReplayIdGet = async (replayId: string, options?: RequestInit): Promise<getReplayFileReplaysReplayIdGetResponse> => {

  const res = await fetch(getGetReplayFileReplaysReplayIdGetUrl(replayId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getReplayFileReplaysReplayIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getReplayFileReplaysReplayIdGetResponse
}



export type getReplayInfoReplaysReplayIdInfoGetResponse200 = {
  data: unknown
  status: 200
}

export type getReplayInfoReplaysReplayIdInfoGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getReplayInfoReplaysReplayIdInfoGetResponseSuccess = (getReplayInfoReplaysReplayIdInfoGetResponse200) & {
  headers: Headers;
};
export type getReplayInfoReplaysReplayIdInfoGetResponseError = (getReplayInfoReplaysReplayIdInfoGetResponse422) & {
  headers: Headers;
};

export type getReplayInfoReplaysReplayIdInfoGetResponse = (getReplayInfoReplaysReplayIdInfoGetResponseSuccess | getReplayInfoReplaysReplayIdInfoGetResponseError)

export const getGetReplayInfoReplaysReplayIdInfoGetUrl = (replayId: string,) => {




  return `http://localhost:8080/replays/${replayId}/info`
}

/**
 * @summary Get Replay Info
 */
export const getReplayInfoReplaysReplayIdInfoGet = async (replayId: string, options?: RequestInit): Promise<getReplayInfoReplaysReplayIdInfoGetResponse> => {

  const res = await fetch(getGetReplayInfoReplaysReplayIdInfoGetUrl(replayId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getReplayInfoReplaysReplayIdInfoGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getReplayInfoReplaysReplayIdInfoGetResponse
}



export type uploadModelModelsPostResponse200 = {
  data: Model
  status: 200
}

export type uploadModelModelsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type uploadModelModelsPostResponseSuccess = (uploadModelModelsPostResponse200) & {
  headers: Headers;
};
export type uploadModelModelsPostResponseError = (uploadModelModelsPostResponse422) & {
  headers: Headers;
};

export type uploadModelModelsPostResponse = (uploadModelModelsPostResponseSuccess | uploadModelModelsPostResponseError)

export const getUploadModelModelsPostUrl = () => {




  return `http://localhost:8080/models/`
}

/**
 * @summary Upload Model
 */
export const uploadModelModelsPost = async (bodyUploadModelModelsPost: BodyUploadModelModelsPost, options?: RequestInit): Promise<uploadModelModelsPostResponse> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadModelModelsPost.file);
formData.append(`name`, bodyUploadModelModelsPost.name);
formData.append(`version`, bodyUploadModelModelsPost.version);
if(bodyUploadModelModelsPost.tags !== undefined) {
 bodyUploadModelModelsPost.tags.forEach(value => formData.append(`tags`, value));
 }
formData.append(`description`, bodyUploadModelModelsPost.description);

  const res = await fetch(getUploadModelModelsPostUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: uploadModelModelsPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadModelModelsPostResponse
}



export type listModelsModelsGetResponse200 = {
  data: unknown
  status: 200
}

export type listModelsModelsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listModelsModelsGetResponseSuccess = (listModelsModelsGetResponse200) & {
  headers: Headers;
};
export type listModelsModelsGetResponseError = (listModelsModelsGetResponse422) & {
  headers: Headers;
};

export type listModelsModelsGetResponse = (listModelsModelsGetResponseSuccess | listModelsModelsGetResponseError)

export const getListModelsModelsGetUrl = (params?: ListModelsModelsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8080/models/?${stringifiedParams}` : `http://localhost:8080/models/`
}

/**
 * @summary List Models
 */
export const listModelsModelsGet = async (params?: ListModelsModelsGetParams, options?: RequestInit): Promise<listModelsModelsGetResponse> => {

  const res = await fetch(getListModelsModelsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listModelsModelsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listModelsModelsGetResponse
}



export type getModelFileModelsModelIdGetResponse200 = {
  data: unknown
  status: 200
}

export type getModelFileModelsModelIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getModelFileModelsModelIdGetResponseSuccess = (getModelFileModelsModelIdGetResponse200) & {
  headers: Headers;
};
export type getModelFileModelsModelIdGetResponseError = (getModelFileModelsModelIdGetResponse422) & {
  headers: Headers;
};

export type getModelFileModelsModelIdGetResponse = (getModelFileModelsModelIdGetResponseSuccess | getModelFileModelsModelIdGetResponseError)

export const getGetModelFileModelsModelIdGetUrl = (modelId: string,) => {




  return `http://localhost:8080/models/${modelId}`
}

/**
 * @summary Get Model File
 */
export const getModelFileModelsModelIdGet = async (modelId: string, options?: RequestInit): Promise<getModelFileModelsModelIdGetResponse> => {

  const res = await fetch(getGetModelFileModelsModelIdGetUrl(modelId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getModelFileModelsModelIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getModelFileModelsModelIdGetResponse
}



export type getModelInfoModelsModelIdInfoGetResponse200 = {
  data: Model
  status: 200
}

export type getModelInfoModelsModelIdInfoGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getModelInfoModelsModelIdInfoGetResponseSuccess = (getModelInfoModelsModelIdInfoGetResponse200) & {
  headers: Headers;
};
export type getModelInfoModelsModelIdInfoGetResponseError = (getModelInfoModelsModelIdInfoGetResponse422) & {
  headers: Headers;
};

export type getModelInfoModelsModelIdInfoGetResponse = (getModelInfoModelsModelIdInfoGetResponseSuccess | getModelInfoModelsModelIdInfoGetResponseError)

export const getGetModelInfoModelsModelIdInfoGetUrl = (modelId: string,) => {




  return `http://localhost:8080/models/${modelId}/info`
}

/**
 * @summary Get Model Info
 */
export const getModelInfoModelsModelIdInfoGet = async (modelId: string, options?: RequestInit): Promise<getModelInfoModelsModelIdInfoGetResponse> => {

  const res = await fetch(getGetModelInfoModelsModelIdInfoGetUrl(modelId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getModelInfoModelsModelIdInfoGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getModelInfoModelsModelIdInfoGetResponse
}
